# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookBridge' do
  use_frameworks! :linkage => :static
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true

  pod 'FirebaseAuth'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwift'
  pod 'KakaoSDKUser'
  pod 'KakaoSDKAuth'

  # Add the Firebase pod for Google Analytics
  pod 'FirebaseAnalytics'

  # For Analytics without IDFA collection capability, use this pod instead
  # pod ‘Firebase/AnalyticsWithoutAdIdSupport’

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
    

  target 'BookBridgeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookBridgeUITests' do
    # Pods for testing
  end

end
