# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
use_frameworks!

target 'BookBridge' do
  use_frameworks! :linkage => :static
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true

  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwift'
  pod 'KakaoSDKUser'
  pod 'KakaoSDKAuth'
  pod 'naveridlogin-sdk-ios'
  pod 'Alamofire'
  pod 'NMapsMap'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'GeoFire', '~> 5.0'
  pod 'FirebaseMessaging'

  # Add the Firebase pod for Google Analytics
  pod 'FirebaseAnalytics'

  # For Analytics without IDFA collection capability, use this pod instead
  # pod ‘Firebase/AnalyticsWithoutAdIdSupport’

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'

  target 'BookBridgeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookBridgeUITests' do
    # Pods for testing
  end

end
